[versions]
activityCompose = "1.9.3"
androidGradlePlugin = "8.7.3"
shizuku = "13.1.5"
bugsnagAndroid = "6.10.0"
bugsnagGradlePlugin = "8.1.0"
compose = "1.7.6"
composeCompiler = "1.5.15"
compose-material3 = "1.3.1"
coreKtx = "1.15.0"
datastorePreferences = "1.1.1"
fastcsv = "3.4.0"
fragmentKtx = "1.8.5"
gson = "2.11.0"
hiddenapibypass = "4.3"
kotlin = "2.1.0"
lifecycleRuntimeKtx = "2.8.7"
material = "1.13.0-alpha09"
patreonsupportersretrieval = "8436bbdbdc"
relinker = "1.4.5"

[libraries]
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
bugsnag-android = { module = "com.bugsnag:bugsnag-android", version.ref = "bugsnagAndroid" }
compose-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "composeCompiler" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "compose-material3" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
fastcsv = { module = "de.siegmar:fastcsv", version.ref = "fastcsv" }
fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtx" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
hiddenapibypass = { module = "org.lsposed.hiddenapibypass:hiddenapibypass", version.ref = "hiddenapibypass" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
material = { module = "com.google.android.material:material", version.ref = "material" }
patreonSupportersRetrieval = { module = "com.github.zacharee:PatreonSupportersRetrieval", version.ref = "patreonsupportersretrieval" }
relinker = { module = "com.getkeepsafe.relinker:relinker", version.ref = "relinker" }
shizuku-api = { module = "dev.rikka.shizuku:api", version.ref = "shizuku" }
shizuku-provider = { module = "dev.rikka.shizuku:provider", version.ref = "shizuku" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
bugsnag = { id = "com.bugsnag.android.gradle", version.ref = "bugsnagGradlePlugin" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
